<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page { margin: 24px; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 9px; color: #1f2937; }
        .header { border-bottom: 2px solid #166534; padding-bottom: 10px; margin-bottom: 14px; }
        .logo { width: 42px; height: 42px; vertical-align: middle; margin-right: 10px; }
        .brand { display: inline-block; vertical-align: middle; }
        .brand-name { font-size: 16px; font-weight: bold; color: #14532d; }
        .brand-subtitle { font-size: 9px; color: #6b7280; }
        h1 { font-size: 15px; margin: 10px 0 0; color: #111827; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #166534; color: #fff; text-align: left; padding: 6px; }
        td { border-bottom: 1px solid #d1d5db; padding: 5px; }
        tr:nth-child(even) td { background: #f0fdf4; }
        .empty { padding: 18px; text-align: center; color: #6b7280; }
        .footer { margin-top: 14px; color: #6b7280; font-size: 8px; }
    </style>
</head>
<body>
    <div class="header">
        @if($logoDataUri)<img class="logo" src="{{ $logoDataUri }}" alt="LG Agri-Tourism logo">@endif
        <div class="brand">
            <div class="brand-name">LG Agri-Tourism</div>
            <div class="brand-subtitle">Inventory Management System</div>
        </div>
        <h1>{{ $title }}</h1>
    </div>
    @if(count($rows))
        <table>
            <thead><tr>@foreach($headers as $header)<th>{{ $header }}</th>@endforeach</tr></thead>
            <tbody>
                @foreach($rows as $row)
                    <tr>@foreach($row as $value)<td>{{ is_numeric($value) && $value !== '' ? number_format((float) $value, 2) : $value }}</td>@endforeach</tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="empty">No active records were found for this month.</div>
    @endif
    <div class="footer">Generated by LG Agri-Tourism Inventory Management System.</div>
</body>
</html>
